version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        - MAGENTO_PUBLIC_KEY=81dad6b4db7c895e80fed91e1a9a6e7e
        - MAGENTO_PRIVATE_KEY=e8522bd8e21ec761530f937c9f5a15ed
    networks:
      - internal
    environment:
      PHP_IDE_CONFIG: serverName=Unnamed
    ports:
      - "80:80"
      - "3000:3000"
      - "30001:3001"
    extra_hosts:
        host.docker.internal: host-gateway
    volumes:
      - varhtml:/var/www/html
      - varetc:/etc
  database:
    container_name: cde-database
    hostname: database
    image: mysql:8.0
    networks:
      - internal
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
  elasticsearch:
    container_name: server-elasticsearch
    hostname: server-elasticsearch
    image: elasticsearch:7.17.14
    expose:
      - "9200"
      - "9300"
    environment:
      - cluster.name=docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - VIRTUAL_HOST=server-elasticsearch
      - HTTP_EXPOSE=9200:9200
      - HTTPS_EXPOSE=9201:9200
    volumes:
      - elasticsearch:/usr/share/elasticsearch
    networks:
      - internal
networks:
  internal:
    driver: bridge
volumes:
  database:
  varhtml:
  varetc:
  redisConf:
  redisData: