version: "3"
services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
      args:
        - MAGENTO_PUBLIC_KEY=81dad6b4db7c895e80fed91e1a9a6e7e
        - MAGENTO_PRIVATE_KEY=e8522bd8e21ec761530f937c9f5a15ed
    networks:
      - internal
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
networks:
  internal:
    driver: bridge
volumes:
  database:
